Complete tasks from other advertisement mode PR
pszklarska/beacon_broadcast pull request #22
Opened 2020-10-19 17:43 UTC by Wisbell

The other PR was sitting for a while, so I went ahead and made the changes.

2020-10-20 23:25 UTC, pszklarska requested changes

2020-10-20 23:25 UTC, pszklarska commented on android/src/main/kotlin/pl/pszklarska/beaconbroadcast/Beacon.kt
> +    val advMode = beaconData.advertiseMode ?: 1
Default value should be made either here (on Kotlin side) or on the Flutter side. Otherwise, it's not obvious where this value should be changed if we'd like to have a different default value.

I'm ok with keeping it here, similar to what's done with `beaconData.transmissionPower`, but then it should be changed in Flutter code to return null when it's not passed:

```
int getCorrespondingInt(AdvertiseMode advMode) {
   switch (advMode) {
     case AdvertiseMode.LOW_POWER:
       return 0;
     case AdvertiseMode.BALANCED:
       return 1;
     case AdvertiseMode.LOW_LATENCY:
       return 2;
     default:
       return null;
   }
```

2020-10-20 23:26 UTC, pszklarska commented
Thanks @Wisbell for your PR! I put some comments, after fixing I'm happy to merge

2020-10-22 22:11 UTC, Wisbell commented
Thanks for the review @pszklarska.  I made the requested changes.  Let me know if there are any other problems.  Also, thanks for this flutter plugin~

2020-10-22 22:36 UTC, pszklarska commented on lib/beacon_broadcast.dart
> +  /// <li>[AdvertiseMode.LOW_POWER] Consumes less energy, but larger broadcast interval
Change to `AdvertiseMode.lowPower`, etc

2020-10-22 22:36 UTC, pszklarska commented on lib/beacon_broadcast.dart
> +  /// This parameter is **Android only** (it has no effect on iOS). It is optional, if not set, the default value will be ADVERTISE_MODE_BALANCED.
Change to: "It is optional, if not set, the default value will be [AdvertiseMode.balanced]"

2020-10-22 22:37 UTC, pszklarska commented
Great! Just last two comments @Wisbell and I think it's all. Thanks!

2020-10-23 20:03 UTC, Wisbell commented on lib/beacon_broadcast.dart
> +  /// This parameter is **Android only** (it has no effect on iOS). It is optional, if not set, the default value will be ADVERTISE_MODE_BALANCED.
Sorry, should have caught those.   All done.

2020-11-03 00:29 UTC, pszklarska approved these changes

2020-11-18 10:11 UTC, merged